services:
  orderprocessing.api:
    image: ${DOCKER_REGISTRY-}orderprocessingapi
    build:
      context: OrderProcessing.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080
      - 8081:8081