services:
  orderprocessing.api:
    image: ${DOCKER_REGISTRY-}orderprocessingapi
    build:
      context: OrderProcessing.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - sqlserver
    networks:
      - orderprocessing 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - orderprocessing

networks:
  orderprocessing:
    driver: bridge

volumes:
  sqlserverdata: